theme = "mono-gray"
icons = "material-nf"

[[block]]
block = "music"
player = "chromium"
buttons = ["play", "next"]

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "disk_space"
path = "/home"
unit = "GB"

[[block]]
block = "sound"

[[block]]
block = "custom"
command = "date '+%A, %d de %B'"
interval = 60

[[block]]
block = "custom"
command = "date '+%I:%M %p'"
interval = 60
