[theme]
name = "semi-native"

[icons]
name = "awesome"

[[block]]
block = "music"
player = "chromium"
buttons = ["play", "next"]

[[block]]
block = "apt"
interval = 600
format = "{count:1} updates available"
format_singular = "{count:1} update available"
format_up_to_date = ""
critical_updates_regex = "(linux|linux-lts|linux-zen)"


[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "sound"

[[block]]
block = "custom"
command = "date '+%A, %d de %B'"
interval = 60

[[block]]
block = "custom"
command = "date '+%I:%M %p'"
interval = 60
