idle_fg = "#afafaf"
info_fg = "#afafaf"
good_fg = "#ffffff"
warning_fg = "#E53935"
critical_fg = "#E53935"
idle_bg = "#000000a0"
info_bg = "#000000a0"
good_bg = "#000000a0"
warning_bg = "#000000a0"
critical_bg = "#000000a0"
